language: objective-c
osx_image: xcode8.1
xcode_workspace: Movies.xcworkspace
xcode_scheme: MoviesTests
xcode_sdk: iphonesimulator10.1
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace Movies.xcworkspace -scheme MoviesTests CODE_SIGNING_REQUIRED=NO
 notifications:
    slack: movies-ios:DeZLwYwsXEmZheWzYgoMhqk7
